### ISSUE TITLE
Customize profile fields

### ISSUE THREAD

**Issue by kevinSuttle** [kevinSuttle/slack#11]
As part of #10, I would love to be able to specify or add custom fields in users' profiles. 

e.g.
- Profile URL
- Twitter URL
- Contact guidelines
- #2

**Comment by kevinSuttle** [comment]
Done! http://slackhq.com/post/132116511325/customprofiles

**Comment by elephino** [comment]
Not sure where else to ask this: Any chance these fields will be available via the API anytime soon?

**Comment by kevinSuttle** [comment]
I would guess you can ask slack.com/help ?
