### ISSUE TITLE
Issue submitting messages with backticks in code blocks

### ISSUE THREAD

**Issue by joshblack** [kevinSuttle/slack#23]
When writing to submit the formatted code block below:

``````
```js
// some js code
``````

If the `When typing code with```, ENTER should not send the message.*` option is selected in a user's preferences, then you can't submit the message through slack. Only way to submit the message is to disable the option.

**Comment by kevinSuttle** [comment]
You just type <kbd>shift</kbd>+<kbd>return</kbd>
